In [2]:
from keras.layers import Input,Dense
from keras.utils import plot_model
from keras.models import Model

In [7]:
visible = Input(shape=(10,))

hidden1 = Dense(10, activation='relu')(visible)
hidden2 = Dense(20, activation='relu')(hidden1)
hidden3 = Dense(10, activation='relu')(hidden2)
output = Dense(1, activation='sigmoid')(hidden3)
model = Model(inputs=visible, outputs=output)
# summarize layers
model.summary()


Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 10)                0         
_________________________________________________________________
dense_13 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_14 (Dense)             (None, 20)                220       
_________________________________________________________________
dense_15 (Dense)             (None, 10)                210       
_________________________________________________________________
dense_16 (Dense)             (None, 1)                 11        
Total params: 551
Trainable params: 551
Non-trainable params: 0
_________________________________________________________________


In [13]:
from keras.layers import Conv2D, MaxPooling2D,Flatten

# Black and white image of dimension 64*64

In [15]:
visible = Input(shape = (64,64,1))
conv1 = Conv2D(32,4,activation ='relu')(visible)
max1 = MaxPooling2D()(conv1)
conv2 = Conv2D(32,4,activation ='relu')(max1)
max2 = MaxPooling2D()(conv2)
flat = Flatten()(max2)
hidden = Dense(10, activation = 'relu')(flat)
output = Dense(1,activation = 'sigmoid')(hidden)
model = Model(inputs = visible, outputs = output)
model.summary()

Model: "model_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         (None, 64, 64, 1)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 61, 61, 32)        544       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 30, 30, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 27, 27, 32)        16416     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_17 (Dense)             (None, 10)                5409

# Upsampling in CNN

upsample to geneate data, tranpose conv layer(apart from upsampling it also learns)

In [41]:
from keras.models import Sequential
from keras.layers import UpSampling2D,Reshape

In [30]:
import numpy as np
from numpy import asarray

In [32]:
x = asarray([[1,2],
             [3,4]]) #2*2 input dimension

In [33]:
x = x.reshape((1,2,2,1)) #no. of examples, img_len, img_wid, gray_scale

In [34]:
print(x)

[[[[1]
   [2]]

  [[3]
   [4]]]]


In [36]:
model = Sequential()
model.add(UpSampling2D(input_shape = (2,2,1)))
model.summary()
y = model.predict(x)
y= y.reshape(4,4)
print(y)

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_2 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [40]:
model = Sequential()
model.add(UpSampling2D(input_shape = (2,2,1)))
model.summary()
y = model.predict(x)
y= y.reshape(8,2)
print(y)

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_5 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1. 1.]
 [2. 2.]
 [1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]
 [3. 3.]
 [4. 4.]]


In [46]:
model = Sequential()
model.add(Dense(128*5*5,input_dim = 100))# 128 total exapmles , 5 *5 img_dim
model.add(Reshape((5,5,128)))
model.add(UpSampling2D())
model.add(Conv2D(1,(3,3),padding = 'same'))
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_21 (Dense)             (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_6 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


# Conv2DTranspose
mapping features to pixels

In [48]:
from keras.layers import Conv2DTranspose

In [50]:
X = asarray([[1, 2],
[3, 4]])

X = X.reshape((1, 2, 2, 1))
# define model
model = Sequential()
model.add(Conv2DTranspose(1, (1,1), strides=(2,2), input_shape=(2, 2, 1)))
# summarize the model
model.summary()
# make a prediction with the model
yhat = model.predict(X)
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))
# summarize output
print(yhat)


Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_2 (Conv2DTr (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________
[[1.5270795 0.        3.054159  0.       ]
 [0.        0.        0.        0.       ]
 [4.5812383 0.        6.108318  0.       ]
 [0.        0.        0.        0.       ]]


# Sample Generator Model

In [54]:
model = Sequential()
model.add(Dense((128 *5*5),input_dim = 100))
model.add(Reshape((5,5,128)))
model.add(Conv2DTranspose(32,3,strides =2 , padding ='same'))
model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_24 (Dense)             (None, 3200)              323200    
_________________________________________________________________
reshape_4 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_3 (Conv2DTr (None, 10, 10, 32)        36896     
Total params: 360,096
Trainable params: 360,096
Non-trainable params: 0
_________________________________________________________________
